# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.2.0"

gem "rails", "~> 7.1.0"
gem "puma", "~> 6.0"
gem "redis", "~> 5.0"
gem "dotenv-rails"

group :development, :test do
  gem "debug"
  gem "rspec-rails"
end
